[project]
name = "hypha-gui"
version = "0.1.0"
dependencies = ["hypha-py"]

[project.scripts]
hypha-gui = "hypha_gui.main:start"

[build-system]
requires = ["uv_build==0.7.13"]
build-backend = "uv_build"
